{{- if and (not .Values.auth.existingSecret) .Values.auth.adminUser .Values.auth.adminPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bytebot-ui.fullname" . }}-auth
  labels:
    {{- include "bytebot-ui.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.usernameKey | quote }}: {{ .Values.auth.adminUser | b64enc | quote }}
  {{ .Values.auth.passwordKey | quote }}: {{ .Values.auth.adminPassword | b64enc | quote }}
{{- end }}
